services:
  haproxy:
    extends:
      file: docker/haproxy.yml
      service: haproxy
  minio:
    extends:
      file: docker/minio.yml
      service: minio
  create-bucket:
    extends:
      file: docker/minio.yml
      service: create-bucket